project:
  type: website

website:
  title: "Econ Apply"
  navbar:
    left:
      - about.qmd
      - href: index.qmd
        text: Econ Applying
      - href: resource.qmd
        text: Econ Resource

format:
  html:
    theme: cosmo
    css: styles.css

execute:
  freeze: auto

